script:
  - wget -q http://gentoo.osuosl.org/releases/x86/autobuilds/latest-stage3-i686.txt
  - wget -q http://gentoo.osuosl.org/releases/x86/autobuilds/$(tail -1 latest-stage3-i686.txt) -O stage3.tar.bz2
  - mkdir gentoo
  - sudo tar xpf stage3.tar.bz2 -C gentoo
  - sudo mount -o bind /dev gentoo/dev
  - sudo mount -t proc none gentoo/proc
  - sudo mount -t sysfs none gentoo/sys
  - sudo chroot gentoo emerge-webrsync
  - sudo chroot gentoo egencache --jobs=9 --repo=gentoo --update --update-use-local-desc